# Site settings
title: Portfolio
email: ebisong@ekababisong.org
#description: ""
baseurl: ""
url: "http://dvdbisong.github.io"
#twitter_username: 
github_username:  dvdbisong

# Google Analytics
google_analytics: UA-89464100-1

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  